### ISSUE TITLE
Falta nombre, descripción y foto

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2021-kata0-prensentacion-muwella#1]
¡Hola @muwella !
Te faltó completar. ¿Tuviste algún problema?
Contanos lo que necesites.

**Comment by muwella** [comment]
Buenas profe! No tengo mi compu hasta mañana, esperaba a ponerme cómoda y poder instalarme todo y arrancar bien

**Comment by asanzo** [comment]
Dale, avisanos cualquier cosa.

**Comment by asanzo** [comment]
Redondo!
